// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../ev-girs
// from ../gir-files
// DO NOT EDIT

use glib::translate::*;

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct SourceLink(Boxed<ffi::PpsSourceLink>);

    match fn {
        copy => |ptr| ffi::pps_source_link_copy(mut_override(ptr)),
        free => |ptr| ffi::pps_source_link_free(ptr),
        type_ => || ffi::pps_source_link_get_type(),
    }
}

impl SourceLink {
    #[doc(alias = "pps_source_link_new")]
    pub fn new(filename: &str, line: i32, col: i32) -> SourceLink {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::pps_source_link_new(
                filename.to_glib_none().0,
                line,
                col,
            ))
        }
    }
}
