// Generated by gir (https://github.com/gtk-rs/gir @ d7c0763cacbc)
// from ../../ev-girs (@ f174c756da94+)
// from ../../gir-files (@ 20031a537e40)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "PpsDocumentView", sizeof(PpsDocumentView), alignof(PpsDocumentView));
    printf("%s;%zu;%zu\n", "PpsDocumentViewClass", sizeof(PpsDocumentViewClass), alignof(PpsDocumentViewClass));
    printf("%s;%zu;%zu\n", "PpsFindSidebar", sizeof(PpsFindSidebar), alignof(PpsFindSidebar));
    printf("%s;%zu;%zu\n", "PpsFindSidebarClass", sizeof(PpsFindSidebarClass), alignof(PpsFindSidebarClass));
    printf("%s;%zu;%zu\n", "PpsMessageArea", sizeof(PpsMessageArea), alignof(PpsMessageArea));
    printf("%s;%zu;%zu\n", "PpsMessageAreaClass", sizeof(PpsMessageAreaClass), alignof(PpsMessageAreaClass));
    printf("%s;%zu;%zu\n", "PpsObjectIface", sizeof(PpsObjectIface), alignof(PpsObjectIface));
    printf("%s;%zu;%zu\n", "PpsObjectManagerClient", sizeof(PpsObjectManagerClient), alignof(PpsObjectManagerClient));
    printf("%s;%zu;%zu\n", "PpsObjectManagerClientClass", sizeof(PpsObjectManagerClientClass), alignof(PpsObjectManagerClientClass));
    printf("%s;%zu;%zu\n", "PpsObjectProxy", sizeof(PpsObjectProxy), alignof(PpsObjectProxy));
    printf("%s;%zu;%zu\n", "PpsObjectProxyClass", sizeof(PpsObjectProxyClass), alignof(PpsObjectProxyClass));
    printf("%s;%zu;%zu\n", "PpsObjectSkeleton", sizeof(PpsObjectSkeleton), alignof(PpsObjectSkeleton));
    printf("%s;%zu;%zu\n", "PpsObjectSkeletonClass", sizeof(PpsObjectSkeletonClass), alignof(PpsObjectSkeletonClass));
    printf("%s;%zu;%zu\n", "PpsPapersApplicationIface", sizeof(PpsPapersApplicationIface), alignof(PpsPapersApplicationIface));
    printf("%s;%zu;%zu\n", "PpsPapersApplicationProxy", sizeof(PpsPapersApplicationProxy), alignof(PpsPapersApplicationProxy));
    printf("%s;%zu;%zu\n", "PpsPapersApplicationProxyClass", sizeof(PpsPapersApplicationProxyClass), alignof(PpsPapersApplicationProxyClass));
    printf("%s;%zu;%zu\n", "PpsPapersApplicationSkeleton", sizeof(PpsPapersApplicationSkeleton), alignof(PpsPapersApplicationSkeleton));
    printf("%s;%zu;%zu\n", "PpsPapersApplicationSkeletonClass", sizeof(PpsPapersApplicationSkeletonClass), alignof(PpsPapersApplicationSkeletonClass));
    printf("%s;%zu;%zu\n", "PpsProgressMessageArea", sizeof(PpsProgressMessageArea), alignof(PpsProgressMessageArea));
    printf("%s;%zu;%zu\n", "PpsProgressMessageAreaClass", sizeof(PpsProgressMessageAreaClass), alignof(PpsProgressMessageAreaClass));
    printf("%s;%zu;%zu\n", "PpsSidebarAnnotations", sizeof(PpsSidebarAnnotations), alignof(PpsSidebarAnnotations));
    printf("%s;%zu;%zu\n", "PpsSidebarAnnotationsClass", sizeof(PpsSidebarAnnotationsClass), alignof(PpsSidebarAnnotationsClass));
    printf("%s;%zu;%zu\n", "PpsSidebarPage", sizeof(PpsSidebarPage), alignof(PpsSidebarPage));
    printf("%s;%zu;%zu\n", "PpsSidebarPageClass", sizeof(PpsSidebarPageClass), alignof(PpsSidebarPageClass));
    return 0;
}
