// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../ev-girs
// from ../../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "PpsProgressMessageArea", sizeof(PpsProgressMessageArea), alignof(PpsProgressMessageArea));
    printf("%s;%zu;%zu\n", "PpsProgressMessageAreaClass", sizeof(PpsProgressMessageAreaClass), alignof(PpsProgressMessageAreaClass));
    return 0;
}
