// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../ev-girs
// from ../gir-files
// DO NOT EDIT

use crate::{ffi, Job};
use glib::{prelude::*, translate::*};

glib::wrapper! {
    #[doc(alias = "PpsJobSignatures")]
    pub struct JobSignatures(Object<ffi::PpsJobSignatures, ffi::PpsJobSignaturesClass>) @extends Job;

    match fn {
        type_ => || ffi::pps_job_signatures_get_type(),
    }
}

impl JobSignatures {
    #[doc(alias = "pps_job_signatures_new")]
    pub fn new(document: &impl IsA<papers_document::Document>) -> JobSignatures {
        assert_initialized_main_thread!();
        unsafe {
            Job::from_glib_full(ffi::pps_job_signatures_new(
                document.as_ref().to_glib_none().0,
            ))
            .unsafe_cast()
        }
    }

    //#[doc(alias = "pps_job_signatures_get_signatures")]
    //#[doc(alias = "get_signatures")]
    //pub fn signatures(&self) -> /*Ignored*/Vec<papers_document::Signature> {
    //    unsafe { TODO: call ffi:pps_job_signatures_get_signatures() }
    //}
}
