// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../ev-girs
// from ../gir-files
// DO NOT EDIT

use crate::ffi;
use glib::translate::*;

#[doc(alias = "pps_get_resource")]
#[doc(alias = "get_resource")]
pub fn resource() -> Option<gio::Resource> {
    assert_initialized_main_thread!();
    unsafe { from_glib_full(ffi::pps_get_resource()) }
}
