// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../ev-girs
// from ../gir-files
// DO NOT EDIT

mod progress_message_area;
pub use self::progress_message_area::ProgressMessageArea;

pub(crate) mod functions;

pub(crate) mod traits {
    pub use super::progress_message_area::ProgressMessageAreaExt;
}
pub(crate) mod builders {
    pub use super::progress_message_area::ProgressMessageAreaBuilder;
}
