// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../ev-girs
// from ../gir-files
// DO NOT EDIT

use glib::{
    prelude::*,
    signal::{connect_raw, SignalHandlerId},
    translate::*,
};
use std::boxed::Box as Box_;

glib::wrapper! {
    #[doc(alias = "PpsPapersWindow")]
    pub struct PapersWindow(Interface<ffi::PpsPapersWindow, ffi::PpsPapersWindowIface>);

    match fn {
        type_ => || ffi::pps_papers_window_get_type(),
    }
}

impl PapersWindow {
    pub const NONE: Option<&'static PapersWindow> = None;

    //#[doc(alias = "pps_papers_window_interface_info")]
    //pub fn interface_info() -> /*Ignored*/Option<gio::DBusInterfaceInfo> {
    //    unsafe { TODO: call ffi:pps_papers_window_interface_info() }
    //}

    //#[doc(alias = "pps_papers_window_override_properties")]
    //pub fn override_properties(klass: /*Ignored*/&mut glib::ObjectClass, property_id_begin: u32) -> u32 {
    //    unsafe { TODO: call ffi:pps_papers_window_override_properties() }
    //}
}

mod sealed {
    pub trait Sealed {}
    impl<T: super::IsA<super::PapersWindow>> Sealed for T {}
}

pub trait PapersWindowExt: IsA<PapersWindow> + sealed::Sealed + 'static {
    //#[doc(alias = "pps_papers_window_call_sync_view")]
    //fn call_sync_view<P: FnOnce(Result<(), /*Ignored*/glib::Error>) + 'static>(&self, arg_source_file: &str, arg_source_point: /*Ignored*/&glib::Variant, arg_timestamp: u32, cancellable: /*Ignored*/Option<&gio::Cancellable>, callback: P) {
    //    unsafe { TODO: call ffi:pps_papers_window_call_sync_view() }
    //}

    //
    //fn call_sync_view_future(&self, arg_source_file: &str, arg_source_point: /*Ignored*/&glib::Variant, arg_timestamp: u32) -> Pin<Box_<dyn std::future::Future<Output = Result<(), /*Ignored*/glib::Error>> + 'static>> {

    //let arg_source_file = String::from(arg_source_file);
    //let arg_source_point = arg_source_point.clone();
    //Box_::pin(gio::GioFuture::new(self, move |obj, cancellable, send| {
    //    obj.call_sync_view(
    //        &arg_source_file,
    //        &arg_source_point,
    //        arg_timestamp,
    //        Some(cancellable),
    //        move |res| {
    //            send.resolve(res);
    //        },
    //    );
    //}))
    //}

    //#[doc(alias = "pps_papers_window_call_sync_view_sync")]
    //fn call_sync_view_sync(&self, arg_source_file: &str, arg_source_point: /*Ignored*/&glib::Variant, arg_timestamp: u32, cancellable: /*Ignored*/Option<&gio::Cancellable>, error: /*Ignored*/Option<glib::Error>) -> bool {
    //    unsafe { TODO: call ffi:pps_papers_window_call_sync_view_sync() }
    //}

    //#[doc(alias = "pps_papers_window_complete_sync_view")]
    //fn complete_sync_view(&self, invocation: /*Ignored*/gio::DBusMethodInvocation) {
    //    unsafe { TODO: call ffi:pps_papers_window_complete_sync_view() }
    //}

    #[doc(alias = "pps_papers_window_emit_closed")]
    fn emit_closed(&self) {
        unsafe {
            ffi::pps_papers_window_emit_closed(self.as_ref().to_glib_none().0);
        }
    }

    #[doc(alias = "pps_papers_window_emit_document_loaded")]
    fn emit_document_loaded(&self, arg_uri: &str) {
        unsafe {
            ffi::pps_papers_window_emit_document_loaded(
                self.as_ref().to_glib_none().0,
                arg_uri.to_glib_none().0,
            );
        }
    }

    //#[doc(alias = "pps_papers_window_emit_sync_source")]
    //fn emit_sync_source(&self, arg_source_file: &str, arg_source_point: /*Ignored*/&glib::Variant, arg_timestamp: u32) {
    //    unsafe { TODO: call ffi:pps_papers_window_emit_sync_source() }
    //}

    #[doc(alias = "closed")]
    fn connect_closed<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn closed_trampoline<P: IsA<PapersWindow>, F: Fn(&P) + 'static>(
            this: *mut ffi::PpsPapersWindow,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(PapersWindow::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"closed\0".as_ptr() as *const _,
                Some(std::mem::transmute::<_, unsafe extern "C" fn()>(
                    closed_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "document-loaded")]
    fn connect_document_loaded<F: Fn(&Self, &str) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn document_loaded_trampoline<
            P: IsA<PapersWindow>,
            F: Fn(&P, &str) + 'static,
        >(
            this: *mut ffi::PpsPapersWindow,
            arg_uri: *mut libc::c_char,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(
                PapersWindow::from_glib_borrow(this).unsafe_cast_ref(),
                &glib::GString::from_glib_borrow(arg_uri),
            )
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"document-loaded\0".as_ptr() as *const _,
                Some(std::mem::transmute::<_, unsafe extern "C" fn()>(
                    document_loaded_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    //#[doc(alias = "handle-sync-view")]
    //fn connect_handle_sync_view<Unsupported or ignored types>(&self, f: F) -> SignalHandlerId {
    //    Ignored invocation: Gio.DBusMethodInvocation
    //    Ignored arg_source_point: GLib.Variant
    //}

    //#[doc(alias = "sync-source")]
    //fn connect_sync_source<Unsupported or ignored types>(&self, f: F) -> SignalHandlerId {
    //    Ignored arg_source_point: GLib.Variant
    //}
}

impl<O: IsA<PapersWindow>> PapersWindowExt for O {}
