name: ARM64 Optimized macOS Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: build-aux/macos

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          /opt/homebrew
          ~/gtk-mac-bundler
          ~/gtk/inst
          ~/gtk/src
        key: ${{ runner.os }}-arm64-pro-${{ hashFiles('papers.modules') }}-v3

    - name: Setup ARM64 environment
      run: |
        # Install Homebrew for ARM
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zshrc
        source ~/.zshrc

    - name: Install core dependencies
      run: |
        arch -arm64 brew install \
          meson \
          ninja \
          cmake \
          gettext \
          pkg-config \
          gtk-mac-integration \
          libarchive \
          poppler \
          djvulibre \
          --formula

    - name: Build gtk-mac-bundler
      run: |
        git clone --depth 1 https://gitlab.gnome.org/GNOME/gtk-mac-bundler.git ~/gtk-mac-bundler
        cd ~/gtk-mac-bundler
        make install
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure build environment
      run: |
        export CC="clang -arch arm64"
        export CXX="clang++ -arch arm64"
        export MACOSX_DEPLOYMENT_TARGET=12.0
        export PKG_CONFIG_PATH="/opt/homebrew/opt/icu4c/lib/pkgconfig:$PKG_CONFIG_PATH"
        
        # Enable parallel builds
        echo "MAKEFLAGS=-j$(sysctl -n hw.ncpu)" >> $GITHUB_ENV
        echo "NINJAFLAGS=-j$(sysctl -n hw.activecpu)" >> $GITHUB_ENV

    - name: Build and package
      run: |
        make clean
        make -j$(sysctl -n hw.activecpu) papers.app
        create-dmg \
          --volname "Papers ARM64" \
          --background Papers.icns \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "papers.app" 200 190 \
          --hide-extension "papers.app" \
          --app-drop-link 600 185 \
          "papers-arm64.dmg" \
          "papers.app/"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Papers-ARM64-Pro
        path: build-aux/macos/papers-arm64.dmg
