name: ARM64 Optimized macOS Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: build-aux/macos

    env:
      PKG_CONFIG_PATH: "/opt/homebrew/lib/pkgconfig:/opt/homebrew/share/pkgconfig"
      LDFLAGS: "-L/opt/homebrew/lib"
      CPPFLAGS: "-I/opt/homebrew/include"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            /opt/homebrew
            ~/gtk-mac-bundler
            ~/gtk/inst
            ~/gtk/src
          key: ${{ runner.os }}-arm64-pro-${{ hashFiles('papers.modules') }}-v4

      - name: Setup ARM64 environment
        run: |
          # Install Homebrew for ARM
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zshrc
          source ~/.zshrc

      - name: Install core dependencies
        run: |
          arch -arm64 brew install \
            meson \
            ninja \
            cmake \
            gettext \
            pkg-config \
            gtk-mac-integration \
            libarchive \
            poppler \
            djvulibre \
            gdk-pixbuf \
            pango \
            cairo \
            fontconfig \
            freetype \
            harfbuzz \
            glib \
            gtk4 \
            --formula \
            --ignore-dependencies

          # Create cross-file if missing
          mkdir -p $GITHUB_WORKSPACE/build-aux/macos
          cat > $GITHUB_WORKSPACE/build-aux/macos/arm64-darwin.txt <<EOF
          [binaries]
          c = 'clang'
          cpp = 'clang++'
          ar = 'ar'
          strip = 'strip'
          pkgconfig = '/opt/homebrew/bin/pkg-config'

          [host_machine]
          system = 'darwin'
          cpu_family = 'aarch64'
          cpu = 'arm64'
          endian = 'little'

          [built-in options]
          c_args = ['-arch', 'arm64', '-I/opt/homebrew/include']
          cpp_args = ['-arch', 'arm64', '-I/opt/homebrew/include']
          pkg_config_path = '/opt/homebrew/lib/pkgconfig'
          EOF

      - name: Configure environment
        run: |
          echo "PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig:/opt/homebrew/share/pkgconfig" >> $GITHUB_ENV
          echo "LDFLAGS=-L/opt/homebrew/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/opt/homebrew/include" >> $GITHUB_ENV

      - name: Build and package
        run: |
          export JH_PREFIX="$HOME/gtk/inst"
          export PROJECT_ROOT="$GITHUB_WORKSPACE"
          export PATH="/opt/homebrew/bin:$PATH"

          meson setup "$PROJECT_ROOT/builddir" "$PROJECT_ROOT" \
            --cross-file="$PROJECT_ROOT/build-aux/macos/arm64-darwin.txt" \
            --prefix="$JH_PREFIX" \
            -Dbuildtype=release

          ninja -C "$PROJECT_ROOT/builddir" install -j$(sysctl -n hw.activecpu)

          cd build-aux/macos
          gtk-mac-bundler papers.bundle \
            --binary="$JH_PREFIX/bin/papers" \
            --resource="$JH_PREFIX/share" \
            --icon=Papers.icns \
            --no-sign

          create-dmg \
            --volname "Papers ARM64" \
            papers-unsigned.dmg \
            papers.app/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Papers-ARM64
          path: build-aux/macos/papers-unsigned.dmg
